"""Render the LLM briefing text into a final BRIEFING.md document."""
from __future__ import annotations

from datetime import datetime, timezone

from briefing.parser import EstateSummary


def format_briefing(llm_text: str, summary: EstateSummary) -> str:
    clouds = ", ".join(c.cloud.upper() for c in summary.clouds)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    counts_table = _counts_table(summary)

    return f"""\
## 🌐 Multi-Cloud Estate Briefing

*Generated: {generated} | Clouds: {clouds}*

{counts_table}

---

{llm_text.strip()}

---
<sub>Generated by [multicloud-estate-briefing](https://github.com/JamesIOmete/multicloud-estate-briefing) · Inventory snapshots: {_snapshot_dates(summary)}</sub>"""


def _counts_table(summary: EstateSummary) -> str:
    header = "| Cloud | VPCs/VNets | Subnets | Sec Groups | Instances | Storage |"
    sep    = "|-------|-----------|---------|------------|-----------|---------|"
    rows = [
        f"| {c.cloud.upper()} | {c.vpc_count} | {c.subnet_count} | {c.security_group_count} | {c.instance_count} | {c.storage_count} |"
        for c in summary.clouds
    ]
    return "\n".join([header, sep] + rows)


def _snapshot_dates(summary: EstateSummary) -> str:
    dates = [c.generated_at for c in summary.clouds if c.generated_at]
    return ", ".join(dates) if dates else "unknown"
